config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  get  'index' =>'messages#index' 
  post 'confirm' => 'messages#confirm'
  post 'done' => 'messages#done' 
  resources :featurings
  resources :producers do
    resources :producer_profiles
  end
  resources :artists do
    resources :artist_profiles
  end
  root "songs#index"
  resources :songs  do
    resources :annotations
    resources :comments, only:[:create,:destroy] do
      resource :favorites, only:[:create,:destroy] 
  end
    collection do
      get 'search'
    end
  end
end

app/models/annotation.rb
class Annotation < ApplicationRecord
  belongs_to :song
  has_one_attached :image
  validates :intention, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :song_artist_relations
  has_many :songs, through: :song_artist_relations
  has_one :artist_profile
  validates :art_name, uniqueness: true
end

app/models/artist_profile.rb
class ArtistProfile < ApplicationRecord
  belongs_to :artist
  has_one_attached :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :song
  belongs_to :user
  has_many :favorites, dependent: :destroy
  validates :text, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  # 一人のユーザーは一回のイイネまで
  validates_uniqueness_of :comment_id, scope: :user_id
end

app/models/featuring.rb
class Featuring < ApplicationRecord
  has_many :songs
  validates :featuring_name,  uniqueness: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'JPOP' },
    { id: 3, name: 'ロック' },
    { id: 4, name: 'ヒップホップ' },
    { id: 5, name: 'R&B' },
    { id: 6, name: 'KPOP' },
    { id: 7, name: 'メタル' },
    { id: 8, name: 'アイドル' },
    { id: 9, name: 'アニメ・ゲーム' },
    { id: 10, name: 'EDM' },
    { id: 11, name: '洋楽pop' },
    { id: 12, name: '洋楽hiphop' },
    { id: 13, name: '洋楽ロック' },
    { id: 14, name: 'その他' }
  ]
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :content

  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 30 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :content, presence: true, length: { maximum: 500 }
end

app/models/producer.rb
class Producer < ApplicationRecord
  has_many :songs
  has_one :producer_profile
  validates :producer_name,  uniqueness: true
end

app/models/producer_profile.rb
class ProducerProfile < ApplicationRecord
  belongs_to :producer
  has_one_attached :image
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  belongs_to :producer, optional: true
  belongs_to :featuring, optional: true
  has_many :song_artist_relations
  has_many :artists, through: :song_artist_relations, dependent: :destroy
  has_one_attached :image
  has_one :annotation
  validates :genre_id, numericality: { other_than: 1 , message: 'を選択してください' }
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre
  has_many :comments
  
  def self.search(search)
    if search != ''
      @song = Song.where('name LIKE(?)', "%#{search}%")
      @text = Song.where('text LIKE(?)', "%#{search}%")
      @translate = Song.where('translate LIKE(?)', "%#{search}%")
      @artist = Artist.where('art_name LIKE(?)', "%#{search}%")
      @producer = Producer.where('producer_name LIKE(?)', "%#{search}%")
      @featuring = Featuring.where('featuring_name LIKE(?)', "%#{search}%")

      @songs = []
      @song.each do |song|
        @songs << song
      end
      @text.each do |text|
        @songs << text
      end
      @translate.each do |translate|
        @songs << translate
      end
      @artist.each do |artist|
        artist.songs.each do |a|
          @songs << a
        end
      end
      @producer.each do |producer|
        producer.songs.each do |pro|
          @songs << pro
        end
      end
      @featuring.each do |featuring|
        featuring.songs.each do |f|
          @songs << f
        end
      end
      @songs = @songs.uniq
      return @songs

    else
      return nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :sns_credentials
  has_many :songs
  has_many :comments
  has_many :favorites, dependent: :destroy

  validates :password, { presence: true, confirmation: true, length: { minimum: 6 } }
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX

  def already_favorited?(comment)
    self.favorites.exists?(comment_id: comment.id)
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
  end

  def confirm
    @message = Message.new(message_params)
    if @message.valid?
      render action: 'confirm'
    else
      render action: 'index'
    end
  end

  def done
    @message = Message.new(message_params)
    if params[:back]
      render action: 'index'
    else
      MessageMailer.received_email(@message).deliver_now
      render action: 'done'
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/featurings_helper.rb
module FeaturingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/messages/confirm.html.erb
<%= form_for @message, :url => done_path do |f| %>
 <div class="reporting-form">
 <%= link_to image_tag("ririkusu-logo.png", class: "ririkusu-icon-new"), "/" %>
    <h2 class="border">内容確認</h2>
    <div class="margin-10px">
      <strong>名前</strong>
      <p>
        <%= f.hidden_field :name %>
        <%= @message.name %>
      </p>
    </div>
    <div class="margin-10px">
      <strong>メールアドレス</strong>
      <p>
        <%= f.hidden_field :email %>
        <%= @message.email %>
      </p>
    </div>
    <div class="margin-10px">
      <strong>お問い合わせ内容</strong>
      <p>
        <%= f.hidden_field :content %>
        <%= simple_format(@message.content) %>
      </p>
    </div>
      <%= f.submit '送信する',class:"confirm_btn"  %>
      <%= f.submit '戻る', name: 'back' ,class:"report-back-btn"%>
  </div>
<% end %>
    

app/views/messages/done.html.erb
<div class="reporting-form">
 <%= link_to image_tag("ririkusu-logo.png", class: "ririkusu-icon-new"), "/" %>
  <h2 class="border">メッセージ送信完了</h2>
  <p>
    <span style="line-height:110%">メッセージをいただきありがとうございました。<br> </span><br>
    
    <span style="line-height:200%">返信は3日以内にお送りさせていただきますので、メール受信ボックスのご確認をよろしくお願いいたします。<br></span><br>
   
    リリクスはお客様の声にお応えし、今後とも改善に努めていきます。引き続き当サイトをお楽しみくださいませ。
  </p>
</div>
   

app/views/messages/index.html.erb
<%= form_for(@message, url: { action: :confirm }) do |f| %>
  <div class="reporting-form">
   <%= link_to image_tag("ririkusu-logo.png", class: "ririkusu-icon-new"), "/" %>
    <h2 class="border">お問い合わせ</h2>

      <% if @message.errors.present? %>
        <div>
          <strong>入力内容にエラーがあります</strong>
          <ul>
            <% @message.errors.each do |attr, error| %>
              <li><%= error %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    <div class="margin-10px">
      <strong>名前</strong>
      <div ><%= f.text_field :name, placeholder: '20文字以内',class:"report-name" %></div>
    </div>
    <div class="margin-10px">
      <strong>メールアドレス</strong>
       <div><%= f.text_field :email, placeholder: '30文字以内',class:"report-name" %></div>
    </div>
    <div class="margin-10px">
      <strong>お問い合わせ内容</strong>
      <div ><%= f.text_area :content, placeholder: '500文字以内 例）通報の場合は、通報したいページのurlの記述のご協力をお願いいたします。' ,class:"report-contents"%></div>
    </div>
      <%= f.submit '確認画面へ',class:"confirm_btn" %>
    
  </div>
<% end %>
 