config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  get  'index' =>'messages#index' 
  post 'confirm' => 'messages#confirm'
  post 'done' => 'messages#done' 
  resources :featurings
  resources :producers do
    resources :producer_profiles
  end
  resources :artists do
    resources :artist_profiles
  end
  root "songs#index"
  resources :songs  do
    resources :annotations
    resources :comments, only:[:create,:destroy] do
      resource :favorites, only:[:create,:destroy] 
  end
    collection do
      get 'search'
    end
  end
end

app/models/annotation.rb
class Annotation < ApplicationRecord
  belongs_to :song
  has_one_attached :image
  validates :intention, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :song_artist_relations
  has_many :songs, through: :song_artist_relations
  has_one :artist_profile
  validates :art_name, uniqueness: true
end

app/models/artist_profile.rb
class ArtistProfile < ApplicationRecord
  belongs_to :artist
  has_one_attached :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :song
  belongs_to :user
  has_many :favorites, dependent: :destroy
  validates :text, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  # 一人のユーザーは一回のイイネまで
  validates_uniqueness_of :comment_id, scope: :user_id
end

app/models/featuring.rb
class Featuring < ApplicationRecord
  has_many :songs
  validates :featuring_name,  uniqueness: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'JPOP' },
    { id: 3, name: 'ロック' },
    { id: 4, name: 'ヒップホップ' },
    { id: 5, name: 'R&B' },
    { id: 6, name: 'KPOP' },
    { id: 7, name: 'メタル' },
    { id: 8, name: 'アイドル' },
    { id: 9, name: 'アニメ・ゲーム' },
    { id: 10, name: 'EDM' },
    { id: 11, name: '洋楽pop' },
    { id: 12, name: '洋楽hiphop' },
    { id: 13, name: '洋楽ロック' },
    { id: 14, name: 'その他' }
  ]
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :content

  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 30 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :content, presence: true, length: { maximum: 500 }
end

app/models/producer.rb
class Producer < ApplicationRecord
  has_many :songs
  has_one :producer_profile
  validates :producer_name,  uniqueness: true
end

app/models/producer_profile.rb
class ProducerProfile < ApplicationRecord
  belongs_to :producer
  has_one_attached :image
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  belongs_to :producer, optional: true
  belongs_to :featuring, optional: true
  has_many :song_artist_relations
  has_many :artists, through: :song_artist_relations, dependent: :destroy
  has_one_attached :image
  has_one :annotation
  validates :genre_id, numericality: { other_than: 1 , message: 'を選択してください' }
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre
  has_many :comments
  
  def self.search(search)
    if search != ''
      @song = Song.where('name LIKE(?)', "%#{search}%")
      @text = Song.where('text LIKE(?)', "%#{search}%")
      @translate = Song.where('translate LIKE(?)', "%#{search}%")
      @artist = Artist.where('art_name LIKE(?)', "%#{search}%")
      @producer = Producer.where('producer_name LIKE(?)', "%#{search}%")
      @featuring = Featuring.where('featuring_name LIKE(?)', "%#{search}%")

      @songs = []
      @song.each do |song|
        @songs << song
      end
      @text.each do |text|
        @songs << text
      end
      @translate.each do |translate|
        @songs << translate
      end
      @artist.each do |artist|
        artist.songs.each do |a|
          @songs << a
        end
      end
      @producer.each do |producer|
        producer.songs.each do |pro|
          @songs << pro
        end
      end
      @featuring.each do |featuring|
        featuring.songs.each do |f|
          @songs << f
        end
      end
      @songs = @songs.uniq
      return @songs

    else
      return nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :sns_credentials
  has_many :songs
  has_many :comments
  has_many :favorites, dependent: :destroy

  validates :password, { presence: true, confirmation: true, length: { minimum: 6 } }
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX

  def already_favorited?(comment)
    self.favorites.exists?(comment_id: comment.id)
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :move_to_login, only: [:new]
  before_action :set_song, only: [:show, :destroy, :edit, :update]
  def index
    @songs = Song.all.includes(:user).order(id: 'DESC')
  end

  def new
    @song = SongsArtist.new
  end

  def create
    
     date = params.require(:songs_artist).permit(:sales_date)
     sales_date = Date.parse(date['sales_date(1i)'] + '-' + date['sales_date(2i)'] + '-' + date['sales_date(3i)'])
     @songg = SongsArtist.new(song_params.merge(sales_date: sales_date))
     url = params[:songs_artist][:youtube_url]
     url = url.last(11)
     @songg.youtube_url = url

    if @songg.valid?
      @song = @songg.save
      render :create
    else
      render :new
    end
  end

  def show
    @song = Song.find(params[:id])
    @annotation = @song.annotation
    @comment = Comment.new
    @comments = @song.comments.includes(:user)
  end

  def edit
    @song = Song.find(params[:id])
    @artist = @song.artists
    @producer = @song.producer
    @featuring = @song.featuring
  end

  def update
    date = params.require(:song).permit(:sales_date)
    sales_date = Date.parse(date['sales_date(1i)'] + '-' + date['sales_date(2i)'] + '-' + date['sales_date(3i)'])
    song = SongsArtist.new(song_update_params.merge(sales_date: sales_date))

    if song.image == nil
     song.image = @song.image.blob 
    end

    if song.valid?
      song.update
      @song = Song.find(params[:id])
      @comment = Comment.new
      @comments = @song.comments.includes(:user)
      render :show
    else
      @song = Song.find(params[:id])
      @artist = @song.artists
      @producer = @song.producer
      @featuring = @song.featuring
      render :edit
    end
  end

  def destroy
    if @song.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @songs = Song.search(params[:keyword])
    @keyword = params[:keyword]
    if @songs== nil
      redirect_to root_path
    end
  end

  def move_to_login
    redirect_to new_user_session_path unless user_signed_in?
  end

  private

  # Create
  def song_params
    params.require(:songs_artist).permit(:name, :text, :image, :translate, :youtube_url, :genre_id, :art_name, :featuring_name, :producer_name).merge(user_id: current_user.id)
  end

  # Update
  def song_update_params
    params.require(:song).permit(:name, :text, :image, :translate, :youtube_url, :genre_id, :art_name, :featuring_name, :producer_name).merge(user_id: current_user.id, song_id: params[:id])
  end

  def set_song
    @song = Song.find(params[:id])
  end
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/featurings_helper.rb
module FeaturingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/create.html.erb
<header class="songs-main-header">
  <%= link_to image_tag("ririkusu-logo.png", class: "ririkusu-icon"), "/" %>
</header>
<div class="create_main">
 <div class="share-propose"><p>投稿できました!</p>
 <p>投稿をシェアしますか？</p></div>
<div class="twitter-share-button-create"><a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></div>
<div class="backbtnn"><%=link_to '投稿内容を確認する',song_path(@song.id) ,class:"back--btn-create"%></div>
<div class="backbtn"><%=link_to 'もどる', root_path, class:"back-btn-create" %></div>


  </div>
<%= render "shared/second-footer"%>

app/views/songs/edit.html.erb
<div class="songs-main-contents">
  <header class="songs-main-header">
    <%= link_to image_tag("ririkusu-logo.png", class: "ririkusu-icon-new"), "/" %>
  </header>
 <div class="songs-main">
    <h2 class="songs-title">歌詞の情報を編集</h2>
      
   <%= form_with model: @song,url:song_path,local: true do |f| %>
   <%= render 'shared/error_messages', model: f.object %>
   
     <%# 商品名と商品説明 %>
      <div class="new-items">
       <div class="weight-bold-text">
         曲名
         <span class="indispensable">(必須)</span>
       </div>
        <%= f.text_area :name, class:"songs-text", id:"item-name", placeholder:"曲名 例）リリスクちゃん", maxlength:"40" %>
       <% @artist.each do |a|%>
       <div class="weight-bold-text">
         歌手名
         <span class="indispensable">(必須)</span>
       </div>
        <%= f.text_area :art_name, class:"songs-text", id:"item-name", value:a.art_name ,placeholder:"歌手名 例）perfurmer", maxlength:"40" %>
        <%end%>
       <div class="weight-bold-text">
         コラボアーティスト
       </div>
       <%= f.text_area :featuring_name, class:"songs-text", id:"item-name", value:@featuring.featuring_name,placeholder:"例） 菅田正樹", maxlength:"40" %>
       <div class="weight-bold-text">
         プロデューサー
       </div>
       <%= f.text_area :producer_name, class:"songs-text", id:"item-name",value:@producer.producer_name,placeholder:"例）中田ヤシタカ", maxlength:"40" %>
    <div class='input-sales-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :sales_date,
                    class:'select-birth',
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: (Time.now.year),
                    end_year: 1930,
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
       <div class="songs-explain">
         <div class="weight-bold-text">
           歌詞
           <span class="indispensable">(必須)</span>
         </div>
         <%= f.text_area :text, class:"songs-text", id:"item-info" ,rows:"7" ,maxlength:"5000" %>
       </div>
       <div class="songs-explain">
         <div class="weight-bold-text">
           和訳
         </div>
         <%= f.text_area :translate, class:"songs-text", id:"item-info" ,rows:"7" ,maxlength:"5000" %>
        </div>
      </div>
      <%# /商品名と商品説明 %>

      <%# 投稿画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
         曲のジャケット写真
         <span class="indispensable">(必須)</span>
        </div>
        <div class="click-upload">
         <div class="flex"> <%= image_tag @song.image,class:"preview-image",id:"default-image" %>
          <%= f.file_field :image, id:"song-image" ,class:"fileupload" %></div>
          <p>
           写真を変更する場合はファイルをアップロード
          </p>
          <div id="image-list"></div>
        </div>
      </div>

     <%# /投稿画像 %>
      <div class="weight-bold-text">
        youtubeのurl
      </div>
      <%= f.text_area :youtube_url, class:"songs-text", id:"item-name", placeholder:"例）https://www.youtube.com/watch?v=DOEk-0MeQbI", maxlength:"100" %>
    
     <%# ジャンル %>
     <div class="songs-detail">
       <div class="weight-bold-text">
          ジャンル
          <span class="indispensable">必須</span>
       </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
     </div>
     <%# /ジャンル%>
     <%# 注意書き %>
     <div class="caution">
       <p class="sentence">
        <a href="#">初めて投稿する人は、投稿ガイド</a>
        で書き方をチェックしてください。
       </p>
     </div>
     <%# /注意書き %>
     <%# 下部ボタン %>
     <div class="submit-btn-contents">
       <%= f.submit "更新する" ,class:"submit-btn", id:"submit" %>
       <%=link_to 'もどる', root_path, class:"back-btn" %>
     </div>
      <%# /下部ボタン %>
  </div>
  <% end %>
</div>
<%= render "shared/second-footer"%>

app/views/songs/index.html.erb
<%= render "shared/header" %>
<div class='main'>
 <div class='song-contents'>
  <p>新着歌詞</p>
  <ul class='song-lists'>
 <% @songs.each do |song| %>
 <li class='song-list' >
 <%= link_to song_path(song.id) ,class:"show_link" do %>
  <div class='song-info'>
   <div class='song-image'>
     <%= image_tag song.image, class: "item-img" %>
   </div>
   <div class='song-name'>
     <%= song.name %>
   </div>
   <div class="song-art-name"><%song.artists.each do |a| %>
      <%=a.art_name%>
   <%end%></div>
  </div>
 <% end %>
 </li>
 <% end %>

 </ul>
 </div>
</div>
<%= render "shared/footer" %>

app/views/songs/new.html.erb
<div class="songs-main-contents">
  <header class="songs-main-header">
    <%= link_to image_tag("ririkusu-logo.png", class: "ririkusu-icon-new"), "/" %>
  </header>
 <div class="songs-main">
    <h2 class="songs-title">歌詞の情報を入力</h2>
      
   <%= form_with model: @song,url: songs_path,local: true do |f| %>
   <%= render 'shared/error_messages', model: f.object %>
   
     <%# 商品名と商品説明 %>
      <div class="new-items">
       <div class="weight-bold-text">
         曲名
         <span class="indispensable">(必須)</span>
       </div>
        <%= f.text_area :name, class:"songs-text", placeholder:"曲名 例）リリスクちゃん", maxlength:"40" %>
       <div class="weight-bold-text">
         歌手名
         <span class="indispensable">(必須)</span>
       </div>
        <%= f.text_area :art_name, class:"songs-text",  placeholder:"歌手名 例）perfurmer", maxlength:"40" %>
       <div class="weight-bold-text">
         プロデューサー
       </div>
       <%= f.text_area :producer_name, class:"songs-text",  placeholder:"例）中田ヤシタカ", maxlength:"40" %>
       <div class="weight-bold-text">
         コラボアーティスト
       </div>
        <%= f.text_area :featuring_name, class:"songs-text", placeholder:"例） 菅田正樹", maxlength:"40" %>
       <div class="weight-bold-text"> 
        リリース日
       <span class="indispensable">(必須)</span>
      </div> 
    <div class='input-sales-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :sales_date,
                    class:'select-birth',
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: (Time.now.year),
                    end_year: 1930,
                    date_separator: '%s'),
                    
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
       <div class="songs-explain">
         <div class="weight-bold-text">
           歌詞
           <span class="indispensable">(必須)</span>
         </div>
         <%= f.text_area :text, class:"songs-text", rows:"7" ,maxlength:"5000" %>
       </div>
       <div class="songs-explain">
         <div class="weight-bold-text">
           和訳
         </div>
         <%= f.text_area :translate, class:"songs-text",rows:"7" ,maxlength:"5000" %>
        </div>
      </div>
      <%# /商品名と商品説明 %>

      <%# 投稿画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
         曲のジャケット写真
         <span class="indispensable">(必須)</span>
        </div>
        <div class="click-upload">
         <p>
           クリックしてファイルをアップロード
         </p>
          <%= f.file_field :image, id:"song-image" %>
          <div id="image-list"></div>
        </div>
      </div>

     <%# /投稿画像 %>
      <div class="weight-bold-text">
        youtubeのurl
      </div>
      <%= f.text_area :youtube_url, class:"songs-text", placeholder:"例）https://www.youtube.com/watch?v=DOEk-0MeQbI", maxlength:"100" %>
    
     <%# ジャンル %>
     <div class="songs-detail">
       <div class="weight-bold-text">
          ジャンル
          <span class="indispensable">必須</span>
       </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
     </div>
     <%# /ジャンル%>
     <%# 注意書き %>
     <div class="caution">
       <p class="sentence">
        <a href="#">初めて投稿する人は、投稿ガイド</a>
        で書き方をチェックしてください。
       </p>
     </div>
     <%# /注意書き %>
     <%# 下部ボタン %>
     <div class="submit-btn-contents">
       <%= f.submit "投稿する" ,class:"submit-btn", id:"submit" %>
       <%=link_to 'もどる', root_path, class:"back-btn" %>
     </div>
      <%# /下部ボタン %>
  </div>
  <% end %>
</div>
<%= render "shared/second-footer"%>

app/views/songs/search.html.erb
<%= render "shared/header" %>


<div class="contents-row">
<div class="hashtag_names">キーワード 「 <span class="keyword_result"><%=@keyword%> </span> 」の曲一覧</div>
<%unless @songs == nil %>
  <div class='song-contents'>
  <ul class='song-lists'>
 <% @songs.each do |song| %>
 <li class='song-list' >
 <%= link_to song_path(song.id) ,class:"show_link" do %>
  <div class='song-info'>
   <div class='song-image'>
     <%= image_tag song.image, class: "item-img" %>
   </div>
   <div class='song-name'>
     <%= song.name %>
   </div>
   <div class="song-art-name"><%song.artists.each do |a| %>
      <%=a.art_name%>
   <%end%></div>

  </div>
 <% end %>
 </li>
 <% end %>

 </ul>
 </div>
    
 <%if @songs.length == 0 %>
   <div class="no_hits">
     <p>検索条件に当たる曲はありませんでした</p>
     <p>登録しますか？</p>
    <div class="addsonglink"> <%= link_to '曲を追加する',new_song_path, class: "addsong-link" %></div>
   </div>
 <%end%>
<%end%>
</div>

</div>

app/views/songs/show.html.erb
<%= render "shared/header" %>

<div class="background">
 <div class="bg-mask">
  <style>
  .background{
   background-image: url(<%= rails_representation_url(@song.image.variant({}), only_path: true) %>);
   background-position: center;
  }
  </style>
  <div class="song_contents">
   <div>
     <%= image_tag @song.image, class: "song_img" %>
   </div>
   <div class="song_names">
    <div class="song_name_text">
      <%= @song.name%>
    </div>
    <div>
     <%@song.artists.each do |art| %>
      <div class="art_name_text"><%= link_to artist_path(art.id) ,class:"show_link" do %><%=art.art_name%></div><%end%>
     <%end%>
     <div class="flex"><div class="art_sorrounded_text">コラボ with</div><div class="sorround_ppl"><%=@song.featuring.featuring_name%></div></div>
     <div class="flex"><div class="art_sorrounded_text">プロデューサー</div><div class="producer_show"><%= link_to producer_path(@song.producer.id) ,class:"show_link" do %><%=@song.producer.producer_name%></div><%end%></div>
     <div class="flex"><div class="art_sorrounded_text">ジャンル</div><div class="sorround_ppl"><%= @song.genre.name %></div></div>
   <div class="flex"><div class="art_sorrounded_text">リリース日</div><div class="sorround_ppl"><%= @song.sales_date%></div></div>
    </div>
    </div>
 </div>
</div>
</div> 
<div class= half>

<div class="song_text">
<% if current_user %>
 <div class="hover"><%= link_to '歌詞を編集する',edit_song_path(@song.id), method: :get, class: "lyric-edit-btn" %></div>
 <% if current_user.id == 1%>
 <%= link_to '削除', song_path(@song.id), method: :delete %>
 <%end%> 
<%end%> 

<p class="plum">歌詞</p><%= @song.text%></div> 
<div class="annotation_space">

<% if @annotation %>

<p class="plum">注釈・考察</p>
 <div> <%= image_tag @annotation.image, class: "annotation_img" if @annotation.image.attached? %></div>
  <%if @annotation.image_text.present?%>
   <div class="font-size"> <%= @annotation.image_text %></div>
  <%end%>
  <%if @annotation.album.present?%>
   <div class="annotation-title">アルバム</div><div class="annotation-margin"><%= @annotation.album%></div>
  <%end%>
  <%if @annotation.sample.present?%>
   <div class="annotation-title">サンプリング</div><div class="annotation-margin"><%= text_url_to_link(h(@annotation.sample)).html_safe %></div>
  <%end%>
  <%if @annotation.message.present?%>
    <div class="annotation-title">曲に込めた意味</div> <div class="annotation-margin"><%= text_url_to_link(h(@annotation.message)).html_safe %></div>
  <%end%>
  <% if @annotation.relationship.present?%>
    <div class="annotation-title">コラボアーティスト/プロデューサーとの関係</div> <div class="annotation-margin"><%= text_url_to_link(h(@annotation.relationship)).html_safe %></div>
  <%end%>
  <%if @annotation.trouble.present?%> 
    <div class="annotation-title">ビーフ・トラブルや噂</div> <div class="annotation-margin"> <%= text_url_to_link(h(@annotation.trouble)).html_safe %></div>
   <%end%>  
  <%if @annotation.slang.present?%>
    <div class="annotation-title">スラング・用語解説</div> <div class="annotation-margin"><%= text_url_to_link(h(@annotation.slang)).html_safe %></div>
  <%end%>
  <%if @annotation.intention.present?%>
   <div class="annotation-title">歌詞の意味・ほのめかし</div> <div class="annotation-margin"> <%= text_url_to_link(h(@annotation.intention)).html_safe %></div>
  <%end%>
  <%if @annotation.info.present?%>   
    <div class="annotation-title">コンサート/パフォーマンス情報</div><div class="annotation-margin"><%= text_url_to_link(h(@annotation.info)).html_safe %></div>
  <%end%>
  <% if @annotation.award.present?%>
    <div class="annotation-title">受賞・チャート歴</div> <div class="annotation-margin"><%= text_url_to_link(h(@annotation.award)).html_safe %></div>
  <%end%> 
 
<%end%> 
</div> 
</div> 

<%unless @song.translate == ""%>
 <div class="song_translate">
 <p>和訳</p>
 <%= @song.translate%>
 </div> 
<%end%> 

<%unless @song.youtube_url == ""%>
<div  class="youtube">
 <div><iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @song.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
</div>
<%end%> 
<div class="comment-box">
  <% if current_user %>
      <%= form_with(model: [@song, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2",class: "comment-text" %>
       <div class="hover"> <button type="submit" class="comment-btn">
        <span>コメントする<span>
      </button></div>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
    <% end %>
  <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
  <% end %>


  <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
      <div id='comments'>
        <% @comments.reverse_each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "#" %>：</strong>
            <%= comment.text %>
            
            <%if user_signed_in?%>
             <% if current_user.already_favorited?(comment)%>
                <%= link_to  "/songs/#{@song.id}/comments/#{comment.id}/favorites", method: :delete do%>
                  <i class="fas fa-thumbs-up thum-icon"></i>
                <%end%>
             <%else%>
               <%= link_to  "/songs/#{@song.id}/comments/#{comment.id}/favorites", method: :post do%>
                 <i class="far fa-thumbs-up thum-icon"></i>
               <%end%>
             <%end%>
            <%end%>
            <%=comment.favorites.count%>
            <% if user_signed_in? %>  
              <% if current_user.id == comment.user_id ||current_user.id ==1%>
               <%= link_to  "/songs/#{@song.id}/comments/#{comment.id}", method: :delete do %>
               <i class="far fa-trash-alt trash-icon"></i>削除
                <%end%>
             <%end%>
           <% end %>
          </p>
        <% end %>
      </div>
      <% end %>
  </div>
</div>

<div class="share-text">記事をシェアする</div><div class="twitter-share"><a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet<img src="/img/social_twitter.png" width="45" alt="twitter">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></div>
  
  <div class="hover"> <%= link_to '通報する', index_path, method: :get, class:'report-song' %></div>
  

 <% if @annotation == nil%>
    <%= link_to "/songs/#{@song.id}/annotations/new" do %>
   <div class="hover-annotation"> <div class='annotation-btn'>
    <span class='annotation-btn-text'><p>注釈を追加する</p><i class="fas fa-marker fa-fw addannotation"></i></span>
   </div></div>
   <%end%>
<%else%>
<%= link_to "/songs/#{@song.id}/annotations/#{@annotation.id}/edit" do %>
   <div class="hover-annotation"> <div class='annotation-btn'>
    <span class='annotation-btn-text'><p>注釈を編集する</p><i class="fas fa-marker fa-fw addannotation"></i></span>
   </div></div>
   <%end%>
<%end%>
 <%= render "shared/footer" %>